import {
  Avatar1,
  Avatar2,
  Avatar3,
  Avatar4,
  Avatar5,
  Avatar6,
  Avatar7,
  Avatar8,
  Avatar9,
  Avatar10,
} from "@/assets/images/users/utils";
import { AgentListingType } from "@/components/realEstate/agent/types";

export const agentListingData: AgentListingType[] = [
  {
    id: 1,
    name: "Dianna Bogan",
    status_type: "Dianna Bogan",
    description: "Especialista em contratos de arrendamento residencial.",
    status: "active",
    select_status: "active",
    new: true,
  },
  {
    id: 2,
    name: "Josefa Weissnat",
    status_type: "Josefa Weissnat",
    description: "Responsável por escritura pública de compra e venda.",
    status: "unActive",
    select_status: "unActive",
    new: false,
  },
  {
    id: 3,
    name: "Ophelia Steuber",
    status_type: "Ophelia Steuber",
    description: "Especialista em registros de imóveis urbanos.",
    status: "active",
    select_status: "active",
    new: false,
  },
  {
    id: 4,
    name: "Federico Hand",
    status_type: "Federico Hand",
    description: "Perito em documentação de hipotecas e garantias.",
    status: "active",
    select_status: "active",
    new: false,
  },
  {
    id: 5,
    name: "Uriel King",
    status_type: "Uriel King",
    description: "Avaliador de certidões negativas e ônus reais.",
    status: "unActive",
    select_status: "unActive",
    new: true,
  },
  // {
  //   id: 6,
  //   joining_date: "18 Feb, 2023",
  //   img: Avatar6,
  //   img_alt: "avatar-6.jpg",
  //   location: "Guarulhos, Brazil",
  //   status_type: "Guarulhos, Brazil",
  //   description: "Consultor em regularização de terrenos e glebas.",
  //   status: "active",
  //   new: false,
  // },
  // {
  //   id: 7,
  //   joining_date: "24 Feb, 2023",
  //   img: Avatar5,
  //   img_alt: "avatar-5.jpg",
  //   name: "Xander Wyman",
  //   status_type: "Xander Wyman",
  //   description: "Especialista em documentos de loteamento e incorporação.",
  //   status: "unActive",
  //   new: true,
  // },
  // {
  //   id: 8,
  //   joining_date: "29 Feb, 2023",
  //   img: Avatar4,
  //   img_alt: "avatar-4.jpg",
  //   name: "Donnell Schultz",
  //   status_type: "Donnell Schultz",
  //   description: "Responsável por dossiês de licenciamento imobiliário.",
  //   status: "active",
  //   new: false,
  // },
  // {
  //   id: 9,
  //   joining_date: "11 Mar, 2023",
  //   img: Avatar3,
  //   img_alt: "avatar-3.jpg",
  //   name: "Jacinthe Will",
  //   status_type: "Jacinthe Will",
  //   description: "Analista de contratos de cessão de direitos.",
  //   status: "active",
  //   new: true,
  // },
  // {
  //   id: 10,
  //   joining_date: "15 Mar, 2023",
  //   img: Avatar2,
  //   img_alt: "avatar-2.jpg",
  //   name: "Josefa Weissnat",
  //   status_type: "Josefa Weissnat",
  //   description: "Perita em documentação para financiamento habitacional.",
  //   status: "unActive",
  //   new: false,
  // },
  // {
  //   id: 11,
  //   joining_date: "17 Mar, 2023",
  //   img: Avatar6,
  //   img_alt: "avatar-6.jpg",
  //   name: "Buck Roberts",
  //   status_type: "Buck Roberts",
  //   description: "Especialista em dossiês para usucapião extrajudicial.",
  //   status: "active",
  //   new: false,
  // },
];
